remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: alxndr's blog
description: Notes and other stuff...

meta:
  owner_url: http://alxndr.blog
  owner_name: Alexander

social:
  twitter_url: https://twitter.com/drwxrxrx
