theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"
date_format: "%Y-%m-%d"

title: alxndr's blog
description: Notes and other stuff...
url: http://alxndr.blog

meta:
  owner_url: http://alxndr.blog
  owner_name: Alexander

social:
  twitter_url: https://twitter.com/drwxrxrx
