plugins:
- jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

date_format: "%Y-%m-%d"

title: Alexander's blog
description: mostly notes to myself
url: http://alxndr.blog
google_analytics: G-RS6J6JRB3C

meta:
  owner_url: http://alxndr.blog
  owner_name: Alexander

social:
  twitter_url: https://twitter.com/drwxrxrx
