remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

repository: alxndr/blog
locale: en-US
date_format: "%Y %B %-d"
title_separator: " • "
title: Alexander's blog
masthead_title: ://alxndr.blog
description: mostly notes to myself
url: https://alxndr.blog
baseurl: /
name: Alexander
logo: /assets/images/alexander-120x120.png
og_image: /assets/images/alexander-120x120.png
paginate: 10

# search with Lunr in the browser...
search: true
lunr:
  search_within_pages: true

author:
  name: Alexander
  bio: a.k.a. `@alxndr` <br/> a.k.a. `@drwxrxrx`
  links:
    - label: photos
      icon: "fab fa-fw fa-instagram"
      url: https://instagram.com/drwxrxrx
    - label: tech/politics
      icon: "fab fa-fw fa-mastodon"
      url: https://mastodon.xyz/@alxndr
      rel: me
    - label: music
      icon: "fab fa-fw fa-mastodon"
      url: https://shakedown.social/@ufo_joe
    - label: Lojban
      icon: "fab fa-fw fa-mastodon"
      url: https://mas.to/@rexsa
    - label: Toki Pona
      icon: "fab fa-fw fa-mastodon"
      url: https://toki.social/@lesate

footer:
  links:
    - label: resume
      icon: "fas fa-fw fa-university"
      url: http://alxndr.github.io/resume/resume.html
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/alxndr
    - label: photos
      icon: "fab fa-fw fa-instagram"
      url: https://instagram.com/drwxrxrx
    - label: tech/politics
      icon: "fab fa-fw fa-mastodon"
      url: https://mastodon.xyz/@alxndr
      rel: me
    - label: music
      icon: "fab fa-fw fa-mastodon"
      url: https://shakedown.social/@ufo_joe
      rel: me
    - label: Lojban
      icon: "fab fa-fw fa-mastodon"
      url: https://mas.to/@rexsa
      rel: me
    - label: Toki Pona
      icon: "fab fa-fw fa-mastodon"
      url: https://toki.social/@lesate
      rel: me

analytics:
  google:
    tracking_id: G-RS6J6JRB3C

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true

plugins:
  - jekyll-archives
  - jekyll-include-cache
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-feed
